version: "3.8"
services:
  sjenkins:
    image: jenkins/jenkins
    ports:
      - 6002:8080
  qaserver:
    image: tomee
    ports:
      - 6001:8080
    links:
      - sjenkins:kjenkins
  prodserver:
    image: tomee
    ports:
      - 6003:8080
    links:
      - sjenkins:kjenkins

